### ISSUE TITLE
pkg update errors on the docker container.

### ISSUE THREAD

**Issue by siriuscn** [myfreeweb/docker-freebsd-cross#1]
$ pkg -r /freebsd update
33 pkg: failed to get the note section
34 pkg: failed to get the note section
35 Updating FreeBSD repository catalogue...
36 Fetching meta.txz: . done
37 pkg: repository meta /freebsd/var/db/pkg/FreeBSD.meta has wrong version 2
38 repository FreeBSD has no meta file, using default settings
39 Fetching packagesite.txz: .......... done
40 pkg: repository meta /freebsd/var/db/pkg/FreeBSD.meta has wrong version 2
41 pkg: Repository FreeBSD load error: meta cannot be loaded No error information
42 Unable to open created repository FreeBSD
43 Unable to update repository FreeBSD
44 Error updating repositories!

**Comment by valpackett** [comment]
Looks like the pkg version here is too old, I'll try updating it..

**Comment by siriuscn** [comment]
How is it now?

**Comment by valpackett** [comment]
Sorry, I was too busy with other stuff

**Comment by valpackett** [comment]
Updated now.
